### ISSUE TITLE
2DECOMP&FFT work:

### ISSUE THREAD

**Issue by pbartholomew08** [xcompact3d/x3div#5]
(we need 2DECOMP&FFT to work as an independent library so it can be maintained properly)
-Github sub-project (Paul), if bad idea then go for external library option

TARGET: Mid-FEB

**Comment by mathrack** [comment]
This issue might be redundant with [https://github.com/xcompact3d/x3div/issues/37](https://github.com/xcompact3d/x3div/issues/37) ?

**Comment by p-costa** [comment]
Dear all,

I hope this is the right place to ask this. If not, my apologies for the spam!

I also wanted to start to incorporate 2DECOMP&FFT in my projects as an external module (using git submodules), and I was wondering which repo to use: https://github.com/numericalalgorithmsgroup/2decomp_fft, or perhaps the repo from Xcompact3d would be the right one to use? If so, I guess I will start with a personal fork of the one in the first link, and then replace it when you have the new 2DECOMP standalone repository.

Thank you,
Pedro

**Comment by pbartholomew08** [comment]
Hi Pedro,

The NAG repo is the "central" repo, we are forked from it and push changes back to them. I think the best would be to fork from their repo (and you can always track additional repositories along the lines of:
``
git remote add x3d_2decomp <url for 2decomp_fft fork>
git pull x3d_2decomp/main
``

Cheers,
Paul

**Comment by p-costa** [comment]
Thank you! It sounds good.

I'd also have some suggestions for minor extensions to the library (e.g., for field data I/O). For proposing suggestions (or even submitting contributions as PR), this would be the right place?

**Comment by pbartholomew08** [comment]
I think this particular repo would be the wrong one - either the Xcompact3d fork of 2decomp&fft (https://github.com/xcompact3d/2decomp_fft) or the NAG one would be better I think to raise issues such as that.

**Comment by pbartholomew08** [comment]
Hi again, after some experimenting, I've created my own fork of Xcompact3d/2decomp_fft - when I then create a pull request you can select from the drop-down which fork you want to contribute to (by default the one you forked from).

**Comment by p-costa** [comment]
Thanks! Good to know. I would first open an issue in the repo anyway (or at least communicate the ideas to the developers), to be sure that the suggestions make sense to be incorporated. And I think that only the NAG one allows for this (I guess because the others are forks).

**Comment by pbartholomew08** [comment]
Ah - I think that may be the case.

I'll close this issue now, as pointed out it is replaced by #37
