### ISSUE TITLE
Finalised "do concurrent" version of x3div:

### ISSUE THREAD

**Issue by pbartholomew08** [xcompact3d/x3div#6]
- [x] Poisson solver (Stefano) 
- [x] Check MPI_ALLTOALL (Stefano)
- [x] CMake/Makefile for NVIDIA flags (Stefano)
- [x] Update Readme for on how to use the Cmake (Stefano)
- [x] Chose best Thomas algo option (Cedric)

TARGET: 04/02/2022

**Comment by mathrack** [comment]
An important new commit associated with the choice of the optimized Thomas algorithm : https://github.com/xcompact3d/x3div/commit/ca529b067f77628db75e2e5190380a9586f29868
