### ISSUE TITLE
Benchmarking:

### ISSUE THREAD

**Issue by pbartholomew08** [xcompact3d/x3div#7]
- [ ] CPU only GCC (Cedric/Sylvain)
- [ ] CPU only Intel (Cedric/Sylvain)
- [ ] CPU only NVIDIA (Stefano)
- [ ] GPU only NVIDIA (Stefano)
- [ ] testing on ARCHER2/GNU (CPU only, Paul)
- [ ] testing on ARCHER2/Cray (CPU only, Paul)
- [ ] testing on ARCHER2/AOCC? (CPU only, Paul)

-->Testing with TGV case with 128^3, 256^3, 512^3 and 1024^3 mesh nodes.

--> Properly document the benchmarking for reproducibility (machine, compiler, option, github version, etc.)

TARGET: End-Feb

**Comment by mathrack** [comment]
Suggestion of csv format following [xcompact3d/X3D-benchmarking/blob/main/benchmarks.csv](https://github.com/xcompact3d/X3D-benchmarking/blob/main/benchmarks.csv) :
``Machine,Label,Nodes,MPI Ranks / Node,Threads / MPI rank,x3div code version,Compiler,MPI library,FFLAGS,FFT library,Precision,Mesh size,prow,pcol,n dt,elapsed time,compute rate``
One GPU = One MPI rank (with one thread)

**Comment by pbartholomew08** [comment]
Sounds good to me. Do you mean that x3div on completion should write such a .csv file?

Also, I think we could add this data to the benchmark repo so it is all kept in one place

**Comment by mathrack** [comment]
IMO, no need to modify x3div

**Comment by mathrack** [comment]
Here is a suggestion for a minor code update associated with the benchmark : https://github.com/xcompact3d/x3div/pull/11

On my test machine:
- CPU only with GCC is not very good compared with MPI
- CPU only with ifort is ok but not as good as MPI
- CPU only with nvidia compiler fails in divergence / interyvp, see error message below

```
Failing in Thread:1
call to cuStreamSynchronize returned error 715: Illegal instruction
```

**Comment by mathrack** [comment]
@rfj82982 could you reproduce the error I have obtained with the nvidia compiler ? It might be specific to my machine or to my installation of the nvidia compiler / environment.

**Comment by rfj82982** [comment]
@mathrack I can try to reproduce the error, just confuse which branch i have to use (hack_doconccurent on which repository)?

**Comment by mathrack** [comment]
I have observed this error with the branch I have proposed ot merge : https://github.com/mathrack/x3div/tree/hack_doconcurrent

I will try to reproduce it with the current do concurrent branch.

**Comment by rfj82982** [comment]
I used @mathrack version of the do concurrent branch and compile it using both GPU and multicore. In both cases it is working. However I am using cmake to compile. I’ll share the listing on slack since I cannot here

**Comment by mathrack** [comment]
@rfj82982 after a bit of extra testing, the code compiled with the nvidia compiler and targetting automatic parallelization on CPU (see compiler options below) can run the case 32x32x32 and 64x64x64. However, it fails on 96x96x96, 128x128x128, 192x192x192 and 256x256x256. I have not tested larger grids.
```
FFLAGS = -cpp -O3 -march=native -Minfo=stdpar -stdpar=multicore -acc
```

**Comment by rfj82982** [comment]
here my flags (using Cmake)
`Fortran_FLAGS = -cpp -Mfree -Kieee -Minfo=accel -g -stdpar -acc -target=multicore -fast -O3`
and it is working. I’ll try now with the Makefile

**Comment by rfj82982** [comment]
Yes the version i compile from make is not working. I think we ned to use 
`-stdpar -target=multicore`
and not
`-stdpar=multicore`

**Comment by rfj82982** [comment]
I would also use 
`-Minfo=accel`
to get some info on what acceleration has been performed. With this stuff like this will appear 
'mpif90 -cpp -O3 -march=native -Minfo=accel -stdpar -acc -target=multicore  -I./src -I./decomp2d -cpp -O3 -march=native -Minfo=accel -stdpar -acc -target=multicore  -DDOUBLE_PREC -DVERSION=\"v0.0-76-ga3948be\"   -c src/transeq.f90
momentum_rhs_eq:
    102, Generating Multicore code
        102, Loop parallelized across CPU threads
    116, Generating Multicore code
        116, Loop parallelized across CPU threads
    131, Generating Multicore code
        131, Loop parallelized across CPU threads
    145, Generating Multicore code
        145, Loop parallelized across CPU threads
    158, Generating Multicore code
        158, Loop parallelized across CPU threads
    172, Generating Multicore code
        172, Loop parallelized across CPU threads
    191, Generating Multicore code
        191, Loop parallelized across CPU threads

**Comment by mathrack** [comment]
@rfj82982 sounds good. If you have a working Makefile, please update my PR and merge it. I will then test the resulting code on my machine.
