### ISSUE TITLE
-X3div working with nz=1 (Cedric)

### ISSUE THREAD

**Issue by pbartholomew08** [xcompact3d/x3div#8]
-functions for MPI (brainstorming)

**Comment by mathrack** [comment]
Preliminary support for nz=1 is available in the branch `hack_doconcurrent` following commit de926a5be7bc6a1db8a10fe0e0f1aa32c26b3c9c

**Comment by mathrack** [comment]
2D Taylor-Green vortex with `nz=1` is working and showing an error at machine precision here: https://github.com/mathrack/x3div/commit/dd7cd182c9d0a14ab8329eab2049e4b8a7376ea6
